apiVersion: v1
kind: Service
metadata:
  labels:
    client: tal-omid-stg
    name: tal-omid-stg
    entity: talend-omid-api
    tfo-bill-aimi_id: "196257"
    tfo-bill-account: talend
  name: tal-omid-cip-stg
  namespace: ns-talend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8065
  selector:
    client: tal-omid-stg
    name: tal-omid-stg    
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    client: tal-omid-stg
    name: tal-omid-stg
    entity: talend-omid-api
    tfo-bill-aimi_id: "196257"
    tfo-bill-account: talend
  name: talendapi-omid-stg
  namespace: ns-talend
spec:
  # replicas: 1
  selector:
    matchLabels:
      client: tal-omid-stg
      name: tal-omid-stg      
  template:
    metadata:
      labels:
        client: tal-omid-stg
        name: tal-omid-stg
        tfo-bill-aimi_id: "196257"
        tfo-bill-account: talend
    spec:
      containers:
      - env:
        name: talendapi-omid-stg
        image: "us-central1-docker.pkg.dev/tfo-us-dev-scbpo-techarch/talend-repo/talend-omid-api-sept07:v5"
        ports:
        - containerPort: 8065
        resources:
          limits:
            cpu: 1
            memory: 1.5Gi          
          requests:
            cpu: 200m
            memory: 768Mi

      imagePullSecrets:
      - name: gcrsec
      # imagePullSecrets:
      # - name: gcrsec  
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: talendapi-omid-stg-hpa
  labels:
        client: tal-omid-stg        
        tfo-bill-aimi_id: "196257"
        tfo-bill-account: talend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: talendapi-omid-stg
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
